spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth0_authenticator
    username: mcloud_user
    password: admin@123
    driver-class-name: org.postgresql.Driver

  task:
    scheduling:
      pool:
        size: 10

  messages:
    basename: messages
    encoding: UTF-8

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-h6bjevho.us.auth0.com/
          audience: https://api.mcloud.com

auth0:
  namespace: https://api.mcloud.com
  roles-claim: https://api.mcloud.com/roles
  management:
    domain: dev-h6bjevho.us.auth0.com
    client-id: TqXccKgqvMK0vBBnCBU999gtESLAuuz5
    client-secret: SbJ0min8F-DYtVkKeFjB3t0Sn0WAIEoTwh2grym4xPa_zTDjGI447xXbYIIsOOE0
  frontend:
    client-id: o9k5Uv8S5jvNENvsxxvP72p3ZFzg2vFy
    client-secret: TEV5VHt6yap0arw9JWTyDp9dOsqD3989PZlEAKgmfYfF8ofpjnHD31zBqPmwCxu3

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /api-docs/swagger-config
    url: /api-docs
  packages-to-scan: com.mcloud.auth0_authenticator
  paths-to-match: /api/**
