spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth0_authenticator
    username: mcloud_user
    password: sua_senha_secreta
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


