spring:
  datasource:
    url: jdbc:postgresql://mcloud-db.cdasooecklyd.sa-east-1.rds.amazonaws.com:5432/mcloud
    username: MCloud
    password: McloudDb123
    driver-class-name: org.postgresql.Driver

messages:
  basename: messages
  fallback-to-system-locale: false
  web:
    locale: pt_BR
    locale-resolver: fixed

