spring:
  datasource:
    url: jdbc:postgresql://mcloud-db.cdasooecklyd.sa-east-1.rds.amazonaws.com:5432/mcloud
    username: MCloud
    password: McloudDb123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-h6bjevho.us.auth0.com/
          audience: https://api.mcloud.com

messages:
  basename: messages
  fallback-to-system-locale: false
  web:
    locale: pt_BR
    locale-resolver: fixed

auth0:
  namespace: https://api.mcloud.com
  roles-claim: https://api.mcloud.com/roles
  management:
    domain: dev-h6bjevho.us.auth0.com
    client-id: TqXccKgqvMK0vBBnCBU999gtESLAuuz5
    client-secret: SbJ0min8F-DYtVkKeFjB3t0Sn0WAIEoTwh2grym4xPa_zTDjGI447xXbYIIsOOE0

logging:
  level:
    root: INFO
    com.mcloud: DEBUG
