spring:
  profiles:
    active: test

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://dev-h6bjevho.us.auth0.com/
              audience: https://api.mcloud.com

    server:
      port: 8080
      error:
        include-stacktrace: never
        include-message: always
        whitelabel:
          enabled: false

    auth0:
      namespace: https://api.mcloud.com
      roles-claim: https://api.mcloud.com/roles  # New property for ROLES_CLAIM
      management:
        domain: dev-h6bjevho.us.auth0.com
        client-id: TqXccKgqvMK0vBBnCBU999gtESLAuuz5
        client-secret: SbJ0min8F-DYtVkKeFjB3t0Sn0WAIEoTwh2grym4xPa_zTDjGI447xXbYIIsOOE0

      frontend:
        client-id: o9k5Uv8S5jvNENvsxxvP72p3ZFzg2vFy
        client-secret: TEV5VHt6yap0arw9JWTyDp9dOsqD3989PZlEAKgmfYfF8ofpjnHD31zBqPmwCxu3

